export const Action = {
  CREATE_NEW_MENU: "CREATE_NEW_MENU",
  CREATE_NEW_MENU: "CREATE_NEW_MENU",
  GET_MENU_ITEMS: "GET_MENU_ITEMS"
}
export const Mutation = {
  // CREATE_NEW_MENU: "CREATE_NEW_MENU",
  SET_NEW_MENU: "SET_NEW_MENU",
  SET_MENU_ITEMS: "SET_MENU_ITEMS",
  SET_MENU_TYPE: "SET_MENU_TYPE",
  RESET_MENU_ITEMS: "RESET_MENU_ITEMS",
  SET_ERROR: "SET_ERROR",
  CLEAR_ERROR: "CLEAR_ERROR"
}